package com.lifeledger.core.testing

import com.lifeledger.core.model.Account
import com.lifeledger.core.model.AccountType
import com.lifeledger.core.model.Bill
import com.lifeledger.core.model.BillType
import com.lifeledger.core.model.Confidence
import com.lifeledger.core.model.Direction
import com.lifeledger.core.model.Insight
import com.lifeledger.core.model.InsightKind
import com.lifeledger.core.model.InsightSeverity
import com.lifeledger.core.model.InstrumentType
import com.lifeledger.core.model.Investment
import com.lifeledger.core.model.Merchant
import com.lifeledger.core.model.Money
import com.lifeledger.core.model.PaymentMethod
import com.lifeledger.core.model.Recurrence
import com.lifeledger.core.model.SmsRecord
import com.lifeledger.core.model.SourceKind
import com.lifeledger.core.model.Subscription
import com.lifeledger.core.model.Transaction
import com.lifeledger.core.model.TransactionType
import com.lifeledger.core.model.TxnCategory
import java.time.Instant

/**
 * Builders for every domain model, each with defaults realistic enough to stand in for a
 * real Indian bank/UPI transaction. A test only ever overrides the field it cares about,
 * so intent stays visible instead of being buried in ten lines of unrelated setup.
 */

/** A fixed instant shared by every builder default, so unrelated tests don't drift apart. */
private val DEFAULT_INSTANT: Instant = Instant.parse("2026-01-15T10:30:00Z")

fun transaction(
    id: Long = 1,
    amount: Money = Money.ofMajor(499),
    type: TransactionType = TransactionType.PURCHASE,
    direction: Direction = type.direction,
    category: TxnCategory = TxnCategory.SHOPPING,
    subcategory: String? = null,
    paymentMethod: PaymentMethod = PaymentMethod.UPI,
    occurredAt: Instant = DEFAULT_INSTANT,
    merchantId: Long? = 10,
    merchantName: String? = "Amazon",
    rawMerchant: String? = "AMZN*MKTPLACE",
    merchantConfidence: Confidence = Confidence.HIGH,
    accountId: Long? = 1,
    maskedAccount: String? = "XX4521",
    bankCode: String? = "HDFC",
    upiId: String? = "amazon@apl",
    balanceAfter: Money? = Money.ofMajor(15_231),
    referenceNumber: String? = "REF123456789",
    transactionId: String? = null,
    description: String? = null,
    notes: String? = null,
    smsId: Long? = 100,
    parserId: String? = "hdfc_debit_v1",
    parserConfidence: Confidence = Confidence.HIGH,
    source: SourceKind = SourceKind.SMS,
    userVerified: Boolean = false,
    excludedFromStats: Boolean = false,
    duplicateOfId: Long? = null,
    tagIds: List<Long> = emptyList(),
    createdAt: Instant = DEFAULT_INSTANT,
    updatedAt: Instant = DEFAULT_INSTANT,
): Transaction = Transaction(
    id = id,
    amount = amount,
    type = type,
    direction = direction,
    category = category,
    subcategory = subcategory,
    paymentMethod = paymentMethod,
    occurredAt = occurredAt,
    merchantId = merchantId,
    merchantName = merchantName,
    rawMerchant = rawMerchant,
    merchantConfidence = merchantConfidence,
    accountId = accountId,
    maskedAccount = maskedAccount,
    bankCode = bankCode,
    upiId = upiId,
    balanceAfter = balanceAfter,
    referenceNumber = referenceNumber,
    transactionId = transactionId,
    description = description,
    notes = notes,
    smsId = smsId,
    parserId = parserId,
    parserConfidence = parserConfidence,
    source = source,
    userVerified = userVerified,
    excludedFromStats = excludedFromStats,
    duplicateOfId = duplicateOfId,
    tagIds = tagIds,
    createdAt = createdAt,
    updatedAt = updatedAt,
)

fun merchant(
    id: Long = 10,
    canonicalName: String = "Amazon",
    normalizedKey: String = Merchant.normalizeKey(canonicalName),
    defaultCategory: TxnCategory = TxnCategory.SHOPPING,
    defaultSubcategory: String? = null,
    website: String? = "amazon.in",
    logoHint: String? = null,
    isBuiltIn: Boolean = true,
    isSubscriptionProvider: Boolean = false,
    isBillProvider: Boolean = false,
    isInvestmentProvider: Boolean = false,
    transactionCount: Int = 12,
    firstSeenAt: Instant? = DEFAULT_INSTANT,
    lastSeenAt: Instant? = DEFAULT_INSTANT,
): Merchant = Merchant(
    id = id,
    canonicalName = canonicalName,
    normalizedKey = normalizedKey,
    defaultCategory = defaultCategory,
    defaultSubcategory = defaultSubcategory,
    website = website,
    logoHint = logoHint,
    isBuiltIn = isBuiltIn,
    isSubscriptionProvider = isSubscriptionProvider,
    isBillProvider = isBillProvider,
    isInvestmentProvider = isInvestmentProvider,
    transactionCount = transactionCount,
    firstSeenAt = firstSeenAt,
    lastSeenAt = lastSeenAt,
)

fun account(
    id: Long = 1,
    displayName: String = "HDFC Savings",
    type: AccountType = AccountType.SAVINGS,
    bankCode: String? = "HDFC",
    bankName: String? = "HDFC Bank",
    maskedNumber: String? = "XX4521",
    currency: String = Money.INR,
    lastKnownBalance: Money? = Money.ofMajor(15_231),
    balanceAsOf: Instant? = DEFAULT_INSTANT,
    creditLimit: Money? = null,
    isArchived: Boolean = false,
    colorSeed: Int = 0,
    transactionCount: Int = 42,
    firstSeenAt: Instant? = DEFAULT_INSTANT,
    lastSeenAt: Instant? = DEFAULT_INSTANT,
): Account = Account(
    id = id,
    displayName = displayName,
    type = type,
    bankCode = bankCode,
    bankName = bankName,
    maskedNumber = maskedNumber,
    currency = currency,
    lastKnownBalance = lastKnownBalance,
    balanceAsOf = balanceAsOf,
    creditLimit = creditLimit,
    isArchived = isArchived,
    colorSeed = colorSeed,
    transactionCount = transactionCount,
    firstSeenAt = firstSeenAt,
    lastSeenAt = lastSeenAt,
)

fun subscription(
    id: Long = 1,
    name: String = "Netflix",
    merchantId: Long? = 20,
    amount: Money = Money.ofMajor(649),
    recurrence: Recurrence = Recurrence.MONTHLY,
    category: TxnCategory = TxnCategory.SUBSCRIPTIONS,
    firstChargedAt: Instant? = DEFAULT_INSTANT,
    lastChargedAt: Instant? = DEFAULT_INSTANT,
    nextExpectedAt: java.time.LocalDate? = java.time.LocalDate.of(2026, 2, 15),
    chargeCount: Int = 6,
    status: Subscription.Status = Subscription.Status.ACTIVE,
    confidence: Confidence = Confidence.HIGH,
    userConfirmed: Boolean = false,
    notes: String? = null,
    previousAmount: Money? = null,
    priceChangedAt: Instant? = null,
): Subscription = Subscription(
    id = id,
    name = name,
    merchantId = merchantId,
    amount = amount,
    recurrence = recurrence,
    category = category,
    firstChargedAt = firstChargedAt,
    lastChargedAt = lastChargedAt,
    nextExpectedAt = nextExpectedAt,
    chargeCount = chargeCount,
    status = status,
    confidence = confidence,
    userConfirmed = userConfirmed,
    notes = notes,
    previousAmount = previousAmount,
    priceChangedAt = priceChangedAt,
)

fun bill(
    id: Long = 1,
    name: String = "BESCOM Electricity",
    type: BillType = BillType.ELECTRICITY,
    merchantId: Long? = 30,
    accountId: Long? = 1,
    consumerNumber: String? = "1234567890",
    lastAmount: Money? = Money.ofMajor(1_240),
    averageAmount: Money? = Money.ofMajor(1_180),
    recurrence: Recurrence = Recurrence.MONTHLY,
    lastPaidAt: Instant? = DEFAULT_INSTANT,
    dueDate: java.time.LocalDate? = java.time.LocalDate.of(2026, 2, 5),
    dueDateIsEstimated: Boolean = true,
    amountDue: Money? = Money.ofMajor(1_240),
    status: Bill.Status = Bill.Status.UPCOMING,
    paymentCount: Int = 8,
    reminderEnabled: Boolean = true,
    reminderDaysBefore: Int = 3,
    confidence: Confidence = Confidence.MEDIUM,
): Bill = Bill(
    id = id,
    name = name,
    type = type,
    merchantId = merchantId,
    accountId = accountId,
    consumerNumber = consumerNumber,
    lastAmount = lastAmount,
    averageAmount = averageAmount,
    recurrence = recurrence,
    lastPaidAt = lastPaidAt,
    dueDate = dueDate,
    dueDateIsEstimated = dueDateIsEstimated,
    amountDue = amountDue,
    status = status,
    paymentCount = paymentCount,
    reminderEnabled = reminderEnabled,
    reminderDaysBefore = reminderDaysBefore,
    confidence = confidence,
)

fun investment(
    id: Long = 1,
    name: String = "Axis Bluechip Fund",
    instrumentType: InstrumentType = InstrumentType.SIP,
    folioOrAccount: String? = "1234567/89",
    provider: String? = "Axis Mutual Fund",
    merchantId: Long? = 40,
    totalInvested: Money = Money.ofMajor(60_000),
    totalRedeemed: Money = Money.ZERO,
    manualCurrentValue: Money? = null,
    valueAsOf: Instant? = null,
    units: Double? = 412.35,
    isSip: Boolean = true,
    sipAmount: Money? = Money.ofMajor(5_000),
    sipRecurrence: Recurrence = Recurrence.MONTHLY,
    sipDayOfMonth: Int? = 5,
    nextExpectedAt: java.time.LocalDate? = java.time.LocalDate.of(2026, 2, 5),
    isActive: Boolean = true,
    contributionCount: Int = 12,
    firstInvestedAt: Instant? = DEFAULT_INSTANT,
    lastInvestedAt: Instant? = DEFAULT_INSTANT,
): Investment = Investment(
    id = id,
    name = name,
    instrumentType = instrumentType,
    folioOrAccount = folioOrAccount,
    provider = provider,
    merchantId = merchantId,
    totalInvested = totalInvested,
    totalRedeemed = totalRedeemed,
    manualCurrentValue = manualCurrentValue,
    valueAsOf = valueAsOf,
    units = units,
    isSip = isSip,
    sipAmount = sipAmount,
    sipRecurrence = sipRecurrence,
    sipDayOfMonth = sipDayOfMonth,
    nextExpectedAt = nextExpectedAt,
    isActive = isActive,
    contributionCount = contributionCount,
    firstInvestedAt = firstInvestedAt,
    lastInvestedAt = lastInvestedAt,
)

fun smsRecord(
    id: Long = 100,
    fingerprint: String = "fingerprint-$id",
    sender: String = "AD-HDFCBK-S",
    body: String = "Rs.499.00 debited from A/c XX4521 on 15-01-26 to VPA amazon@apl. Ref 123456789012.",
    receivedAt: Instant = DEFAULT_INSTANT,
    threadId: Long? = 1,
    providerId: Long? = 500,
    status: SmsRecord.ProcessingStatus = SmsRecord.ProcessingStatus.PARSED,
    processedAt: Instant? = DEFAULT_INSTANT,
    parserId: String? = "hdfc_debit_v1",
    source: SourceKind = SourceKind.SMS,
): SmsRecord = SmsRecord(
    id = id,
    fingerprint = fingerprint,
    sender = sender,
    body = body,
    receivedAt = receivedAt,
    threadId = threadId,
    providerId = providerId,
    status = status,
    processedAt = processedAt,
    parserId = parserId,
    source = source,
)

fun insight(
    id: Long = 1,
    kind: InsightKind = InsightKind.CATEGORY_SPIKE,
    severity: InsightSeverity = InsightSeverity.NOTABLE,
    title: String = "Dining spend is up 32% this month",
    body: String = "You spent ₹6,240 on Food & Dining in January, up from ₹4,730 in December.",
    generatedAt: Instant = DEFAULT_INSTANT,
    periodStart: java.time.LocalDate? = java.time.LocalDate.of(2026, 1, 1),
    periodEnd: java.time.LocalDate? = java.time.LocalDate.of(2026, 1, 31),
    category: TxnCategory? = TxnCategory.FOOD,
    merchantId: Long? = null,
    amount: Money? = Money.ofMajor(6_240),
    changePercent: Double? = 0.32,
    evidence: Map<String, String> = mapOf("previousMonth" to "4730.00", "currentMonth" to "6240.00"),
    relatedTransactionIds: List<Long> = listOf(101, 102, 103),
    isDismissed: Boolean = false,
    isPinned: Boolean = false,
    dedupeKey: String = "category_spike:FOOD:2026-01",
): Insight = Insight(
    id = id,
    kind = kind,
    severity = severity,
    title = title,
    body = body,
    generatedAt = generatedAt,
    periodStart = periodStart,
    periodEnd = periodEnd,
    category = category,
    merchantId = merchantId,
    amount = amount,
    changePercent = changePercent,
    evidence = evidence,
    relatedTransactionIds = relatedTransactionIds,
    isDismissed = isDismissed,
    isPinned = isPinned,
    dedupeKey = dedupeKey,
)
